[theme]
# --- WARNA UTAMA ---
base = "light"
primaryColor = "#FFB200"            
backgroundColor = "#F7F9FC"          
secondaryBackgroundColor = "#ffffffa4" 
textColor = "#31333F"                

# --- TIPOGRAFI ---
font = "sans serif"

# --- BENTUK TOMBOL & KOTAK ---
baseRadius = "1rem" 
buttonRadius = "2rem"

# --- PENGATURAN BORDER ---
borderColor = "#E0E0E0"
showWidgetBorder = true

[theme.sidebar]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"